[package]
name = "warp-link"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["quic", "tcp", "wss"]
quic = ["warp-link-transport/quic"]
tcp = ["warp-link-transport/tcp"]
wss = ["warp-link-transport/wss"]

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
warp-link-core = { version = "0.1.0", path = "../warp-link-core" }
warp-link-transport = { version = "0.1.0", path = "../warp-link-transport", default-features = false }

[dev-dependencies]
pushgo-warp-profile = { version = "0.1.0", path = "../pushgo-warp-profile" }
tokio = { workspace = true, features = ["test-util"] }

[target.'cfg(target_os = "windows")'.dependencies]
quinn = { workspace = true, features = ["rustls-ring"] }
rustls = { workspace = true, features = ["ring"] }
tokio-rustls = { workspace = true, features = ["ring"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
quinn = { workspace = true, features = ["rustls-aws-lc-rs"] }
rustls = { workspace = true, features = ["aws_lc_rs"] }
tokio-rustls = { workspace = true, features = ["aws_lc_rs"] }
